### ISSUE TITLE
スキルの増減タグの修正

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [Shick1112/Text2Frame-MV#1]
スキルの増減タグの実装を、以下の通り変更する。
- 操作の指定の`forgot`を`forget`に変更する。
- アクターリストの`パーティ全体`に、`Entire Party`と`パーティ全体`を追加

※ 以前お伝えした仕様から更に追加変更があります。

以下は、修正した版の仕様です。
## (30) スキルの増減
「スキルの増減」は以下のいずれかの記法で組み込むことができます。
- `<ChangeSkill: アクター, 操作, スキルID>`
- `<スキルの増減: アクター, 操作, スキルID>`

アクターリスト
- パーティ全体: `Entire Paty`, `パーティ全体`, `0`, 
- アクターIDを指定: `1以上の整数`
- 変数: `variables[n]`, `変数[n]`

操作リスト
- 覚える: `learn`, `+`, `覚える`
- 忘れる: `forget`, `-`, `忘れる`

例1: アクターID1がスキルID2を覚える
- `<ChangeSkill: 1, learn, 2>`
- `<スキルの増減: 1, 覚える, 2>`

例2: 変数ID4のアクターがスキルID1を忘れる
- `<ChangeSkill: variables[4], forget, 1>`
- `<スキルの増減: 変数[4], 忘れる, 1>`

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 まずは今後の流れを掴んでもらうために、ひとつイシューを立ててみました。
feature/add_change_skillブランチに、テストケースをいれセットアップしているので、こちらのブランチ上で作業をお願いします。
テストの実行方法は、ご存知かと思いますが、
```
npm run test
```
です。
現在の状態ですと、
```
  1) Text2Frame Test
       Change Skill:
     Uncaught Error: Syntax error. / 文法エラーです。:  ChangeSkill: Entire Paty, learn, 1  
      at getFixedOrVariable (Text2Frame.js:7246:17)
      at _getEvents (Text2Frame.js:7679:39)
      at getEvents (Text2Frame.js:8503:20)
      at Game_Interpreter.pluginCommandText2Frame (Text2Frame.js:8685:28)
      at /＜秘密＞/Text2Frame/Shick1112/Text2Frame-MV/test/test_json_eq.js:113:36
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

  2) Text2Frame Test
       Name:
     Uncaught Json syntax error. 
ファイルが壊れています。RPG Makerでプロジェクトをセーブし直してください
/＜秘密＞Text2Frame/Shick1112/Text2Frame-MV/node_modules/mocha/bin/data/Map001.json
  Error: Json syntax error. 
  ファイルが壊れています。RPG Makerでプロジェクトをセーブし直してください
      at readJsonData (Text2Frame.js:3913:15)
      at Game_Interpreter.pluginCommandText2Frame (Text2Frame.js:8703:24)
      at /＜秘密＞/Text2Frame/Shick1112/Text2Frame-MV/test/test_json_eq.js:113:36
      at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
・・・＜省略＞・・・
```
という結果が出るかと思います。2)以降は、1)をパスすると、つまり今回のタグのテストをパスした場合に直るはずです。


これでテストがパスした場合、feature/add_all_tagブランチへのプルリクの発行をお願いします。今の所タグ毎のプルリクの発行を考えていますが、仕様変更がないものについてはまとめてひとつのイシューにするかもしれません。イシューの作業粒度が合わずやりづらい場合は、ご一報ください。適宜調整します。

私はこのようにひたすらテストケースを作成し、イシューを発行していくので、Shickさんは私がすべてのイシューを発行するのを待つ必要はありません。ご自身のご都合のよいタイミングで、都度実装をお願いいたします。なお、やはりテストケースを書いていると仕様がちょっと変更されたりすることがあります。マスターはイシューの仕様なので、そちらを優先してください。

なにか分からないところやお気に召さない点がありましたら、お申し付けください。よろしくお願いします。

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
issueの発行ありがとうございます！
実装、テスト、プルリクの流れは理解できたと思いますので都度作業を進めていきます。
不明な点があったら相談させてください。

以上です。よろしくお願いいたします。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 
おつかれさまです。
すみません、もしまだ本件実装が終わっていないのであれば、変数の指定の代替に`V[n]`というものを加えていただけないでしょうか？
他のタグで変数を指定する場合と統一する方針で開発しているのですが、追加を失念しておりました。

もし実施いただけるのであれば、以下のテストケース１４行目
https://github.com/Shick1112/Text2Frame-MV/blob/feature/add_change_skill/test/actor/change-skill.txt
`<changeskill: variables[100], +, 33>`
を
`<changeskill: V[100], +, 33>`
と修正していただけないでしょうか。

大変お手数をおかけします。

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi
了解しました。
テストケースを記載していただいたとおりに修正してからテストします。

以上です。よろしくお願いいたします。
