### ISSUE TITLE
マップのスクロールタグの修正

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [Shick1112/Text2Frame-MV#2]
マップのスクロールタグを、以下の通り変更する。
- 完了までウェイトを、MVという指定をなくして、省略可能にする。
- ウェイトリストのONに、以下を追加
  - `Wait for Completion`
  - `完了までウェイト`
  - `Wait`
- 速度の指定を以下のように変更
  - `x8slower`->  `x8 slower`
  -  `x4slower`->  `x4 slower`
  - 以下同様

以下は、修正した版の仕様です。
## (39) マップのスクロール
「マップのスクロール」は以下のいずれかの記法で組み込むことができます。
- `<ScrollMap: 方向, 距離, 速度, 完了までウェイト>`
- `<マップのスクロール: 方向, 距離, 速度, 完了までウェイト>`

向きリスト
- 下: `down`, `2`, `下`
- 左: `left`, `4`, `左`
- 右: `right`, `6`, `右`
- 上: `up`, `8`, `上`

距離リスト
- `1`以上の整数

速度
- 1/8倍速: `x8slower`, `1`, `1/8倍速`
- 1/4倍速: `x4slower`, `2`, `1/4倍速`
- 1/2倍速: `x2slower`, `3`, `1/2倍速`
- 標準速: `normal`, `4`, `標準速`
- 2倍速: `x2faster`, `5`, `2倍速`
- 4倍速: `x4faster`, `6`, `4倍速`

完了までウェイトリスト（省略可能）
- チェックオン: `Wait for Completion`, `完了までウェイト`, `Wait`, `true`, `1`, `オン`, `ON`
- チェックオフ: `false`, `0`, `オフ`, `OFF`, 省略

`完了までウェイト`は省略可能です。その場合は、チェックオフとなります。
また、`完了までウェイト`をオンにするのはツクールMZの機能です。

例1: 下方向の距離100、標準速でマップをスクロール 完了までウェイトしない
- `<ScrollMap: down, 100, normal>`
- `<マップのスクロール: 下, 100, 標準速>`
- `<ScrollMap: down, 100, normal, false>`
- `<マップのスクロール: 下, 100, 標準速, オフ>`

例2: 右方向の距離50、1/2倍速でマップをスクロール 完了までウェイト
- `<ScrollMap: right, 50, x2slower, Wait for Completion>`
- `<ScrollMap: right, 50, x2slower, Wait>`
- `<ScrollMap: right, 50, x2slower, ON>`
- `<マップのスクロール: 右, 50, 1/2倍速, true>`
- `<ScrollMap: right, 50, x2slower, オン>`
- `<マップのスクロール: 右, 50, 1/2倍速, オン>`

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
お疲れ様です。

「完了までウェイト」の省略についての確認なのですが、以下の仕様で合っていますでしょうか？
・MVの場合は「完了までウェイト」を省略する。
・MZの場合は「完了までウェイト」をオンかオフか指定する。

MVとMZでparametersの数が違うようなので、MVかMZかを判定する箇所が必要になると思います。
※プラグイン内の共通処理でMVかMZを判別できるところがあったらすいません！
■マップのスクロール(MV)
{"code":204,"indent":0,"parameters":[2,1,4]}

■マップのスクロール(MZ)
・「完了までウェイト」にチェック無
{"code":204,"indent":0,"parameters":[2,1,4,false]}
・「完了までウェイト」にチェック有
{"code":204,"indent":0,"parameters":[2,1,4,true]}

以上です。よろしくお願いいたします。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 もっともなご指摘ありがとうございます。
マップのスクロール処理は、**MVの場合とMZの場合で処理を分ける必要はありません。**

まず前提としまして、以下の公式サイトの通り、MVとMZはかなり強い互換性があります。イベント処理が書かれていると想定されるMapについても、特に必要な変換はなく、そのまま上書きされるように説明されています。
https://tkool.jp/mz/course/convert/convert.html

なぜこうなるのかというと、MVの場合とMZの場合それぞれでどうなるかを説明します。
- MVの場合
MVの場合、動作懸念があるのは、{"code":204,"indent":0,"parameters":[2,1,4,false]}や{"code":204,"indent":0,"parameters":[2,1,4,true}と言った場合の、parametersの値の配列の要素数が4の場合かと思います。MVのエディタから編集した場合、4つめのウェイトのオプションはないので、要素数は3になります。これ、実際に実行したら分かるのですが、要素数が4の場合は、その４つ目の要素の値は無視されて動作します。つまり、MZの仕様の要素数4の場合でも問題なく動作します（実際に確認済みです）。

- MZの場合
MZの場合にparametersの配列の要素数が3つの場合どうなるかというと、ここでも実は問題なく動作します。4つめの値がない場合、それは false とみなされ、処理されます。そのため、MVの処理前提で用意しても問題はないのです。

以上の２つの前提を踏まえますと、MV/MZの場合でparametersの数を場合分けする必要がなく、MZの仕様、つまりparametersの要素数を4つとした場合に合わせてイベントコマンドとして組み込んであげれば、いずれの場合でも問題がないことになります。MVの場合は、4つ目が使われることなく無視されるだけなので。

MVで動作させたときにMVの仕様100%にならない、というのを気持ち悪く感じる人もいるかとは思うのですが、Text2Frameとしては、処理の一貫性を重視したいと考えており、可能な限りMV/MZで処理を分けるといったことはしておりません。MZ用の機能のタグ（例えばメッセージの表示での名前タグ等）を指定して、MVで実行しても、結果は同じになります。ご理解いただけますと幸いです。
（一点補足すると、アニメーションの表示は実はMV/MZで仕様が違う可能性があるので、そこだけはもう少し調査して仕様を精査したいと考えています。もしかしたらこれだけは特別なことをするかもしれません）

> MVとMZでparametersの数が違うようなので、MVかMZかを判定する箇所が必要になると思います。

そのため、ご指摘いただいたこちらについては、判定する必要はない、という回答になります。Shickさんにも、MV/MZの違いを意識する必要なく、このまま実装していただければと思います。

よろしくお願いします

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
丁寧な説明ありがとうございます！
RPGツクールの処理に問題ないこと、及びText2Frameの方針について理解しました。
MV/MZで処理を分けずに実装致します。

以上です。
