### ISSUE TITLE
ヘルプ文の記述

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [Shick1112/Text2Frame-MV#35]
Text2Frame.js 内のヘルプドキュメントを更新する。

- [x] wikiのタグ紹介の更新
- [x] 新タグのヘルプドキュメントへの追記
- [x] スペシャルサンクスのヘルプドキュメントへの追記
- [x] wiki にのせる全タグ動作確認ようテキストの作成
- [x] wiki に載せるタグ毎のスクショの撮影と貼り付け

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 お疲れ様です。
ついにすべてのタグについてテストをパスしました！大変な作業でしたが、本当にありがとうございます！

残作業はText2Frame内のヘルプ文の書き換えですが、これは私が担当します。

一つ質問なのですが、Text2Frame.js内のauthor に、Shickさんを追記したいのですが、表記名をどうしましょうか？
希望の表記名を教えてください。

よろしくおねがいします。

**Comment by HidetoshiKawaguchi** [comment]
@yktsr すみません、作者欄にお名前を記載しようと思ったのですが、スペースの都合上入りそうにありませんでした。そのため、ヘルプドキュメント内に「協力者」や「スペシャルサンクス」という何らかの形で記載したいと思います。いずれにしても、希望の表記名を教えていただければと思います。

よろしくおねがいします。

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
協力者の表記名ということなら「inazumasoft:Shick」でお願いできますか？
それが長いということなら「Shick」で大丈夫です。
※authorの場合はサークル名を入れたりするのは一般的じゃないのかな～と思ったのですが、
　「協力者」や「スペシャルサンクス」の記載ならサークル名入っていても大丈夫ですかね？

以上です。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 承知しましたー。ヘルプ文だと実質無制限に文字を入れることができるので、サークル名も入れて表記させていただきます。

※ ↑のメンション先、間違えてましたね。失礼しました

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 こんなかんじで、Text2Frame本体のヘルプドキュメントの末尾にある連絡先の一つ前に、「コントリビューター」という節を設けて記載します。なにか不都合や至らない点がありましたら、お申し付けください。
よろしくおねがいします。
```
 --------------------------------------
 コントリビューター
 --------------------------------------
 当プラグインの実装には、以下の方に多大な貢献をいただきました。
 追加機能としてすべてのイベントコマンドをタグで記述できるようになったのは、
 この方の貢献が非常に大きいです。感謝いたします。

   inazumasoft:Shick 様

--------------------------------------
 連絡先
 --------------------------------------
（省略）
 ```

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
何も問題ありません！
こんなにしっかり記載頂いて嬉しいです。

**Comment by yktsr** [comment]
@HidetoshiKawaguchi 
いなずまソフトさんのHPやXのアカウント名は、READMEか、ヘルプ文に記載するのはどうでしょう。ご本人のご希望にもよりますが…

**Comment by HidetoshiKawaguchi** [comment]
@yktsr たしかにそうですね。追記できそうなことは追記したほうがいいですね。
@Shick1112
お名前のほかに、なにか追記してほしいものがありましたらお申し付けください。ヘルプ文（とREADMEにも）に追記させていただきます。
※ 年齢制限や過激な描写があるページへの直リンクはこちらの判断でお断りする可能性はあります

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 作業が完了したので一旦クローズしますが、追記してほしいことがありましたらいつでもご連絡ください。

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
それでは連絡先に以下のcienのURLを追加してもらえますか？
内容はRPGツクールの制作支援であり、過激な画像や記載等もありません。
https://ci-en.net/creator/12715
