### ISSUE TITLE
戦闘の処理

### ISSUE THREAD

**Issue by HidetoshiKawaguchi** [Shick1112/Text2Frame-MV#4]
以下を変更する

- 逃走可と敗北可の引数を削除
- 敵グループの指定方法
- `<IfEnd>`タグを`<End>`タグに変更。

以下に、新しい仕様の詳細を示します。

## (70) 戦闘の処理
「戦闘の処理」は以下の記法で組み込むことができます。
```
<BattleProcessing: 敵グループ>
<IfWin>
勝利した時の処理
<IfEscape>
逃走したときの処理
<IfLose>
敗北したときの処理
<End>
```

`BattleProcessing`は`戦闘の処理`でも代替できます。
また、`IfWin`は`勝ったとき`、`IfEscape`は`逃げたとき`、`IfLose`は`負けたとき`、`End`は`分岐終了`で代替できます。

敵グループは、以下の３種類の指定方法があります。
- 直接指定: `敵グループID`
- 変数の指定: `Variables[変数ID]`, `変数[変数ID]`, `V[変数ID]`
- ランダムエンカウント: `Random`, `ランダム`

`<IfWin>`タグ、`<IfEscape>`タグ、`<IfLose>`タグは省略可能です。
また、これら3つをすべて省略したときに限り、`<End>`タグも省略可能です。

以下に具体例を示します。

例1: 敵グループID1とエンカウント 逃走不可 敗北不可
- `<BattleProcessing: 1>`
- `<戦闘の処理: 1>`

例2: 変数ID5の敵グループとエンカウント 逃走可 敗北可
```
<BattleProcessing: Variables[5]>
<IfWin>
勝った！
<IfEscape>
逃げた！
<IfLose>
負けた！
<End>
```
または
```
<戦闘の処理: 変数[5]>
<勝ったとき>
勝った！
<逃げたとき>
逃げた！
<負けたとき>
負けた！
<分岐終了>
```

例3: ランダムな敵グループとエンカウント 敗北可
```
<BattleProcessing: Random>
<IfWin>
勝った！
<IfLose>
負けた！
<End>
```
または
```
<戦闘の処理: ランダム>
<勝ったとき>
勝った！
<負けたとき>
負けた！
<分岐終了>
```

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
お疲れ様です。

> 逃走可と敗北可の引数を削除

こちらの仕様なのですが、どうコーディングしようか悩んでいます。
`<BattleProcessing: 敵グループ>`のみだと以下のようになり、
{"code":301,"indent":0,"parameters":[0,1,false,false]}
`<IfEscape>や<IfLose>`が存在した場合に、
{"code":301,"indent":0,"parameters":[0,1,true,true]}
というようになると思います。

Text2Frameの仕組みについてについて全て理解できておらず、
調査・実装しても無駄なコーディングになる可能性があるなーと思いましたので、
どのあたりのコードに手を入れればいいのかご教示いただけないでしょうか。

以上です。よろしくお願いいたします。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 ご質問ありがとうございます。
本件、一旦実装をストップしていただけないでしょうか。結構根の深そうな問題です。

私も実装を見直してみたのですが、これはなかなか厄介そうな実装が必要ですね。というのも、Text2Frameは基本的に、テキストを上から順にイベントのコマンド（Frame)に置き換えていってます。これまでは、後続の文章の結果によって内容が変わるというケースがありませんでした。つまり、後ろのテキストを読み込んでいる時に、前にすでに変換されたイベントを書き換えるという処理を行っていません。

ということもあり、かなり基本的な処理を見直す必要がありそうです。どうするかの方針はちょっと考えてみますので、お時間をください。少なくとも、本実装は他のタグがすべて終わったあとに実施したほうがいいと現段階では考えております。別のイシューの実施をお願いいたします。

**Comment by HidetoshiKawaguchi** [comment]
どうするか考えているうちに、大事なテストケース（入れ子の場合）を加えることを忘れていることに気づいたので、また忘れないうちにプッシュしておきました。

**Comment by yktsr** [comment]
検討ありがとうございます。お答えします。
まず、状態を含め、全体処理を司るのが、getEventsです。これは一行のテキストを受け取り、
https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8509

command_list（frame_list）を返します。

https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8592
このcommand_listがそれまでのcommand_listと concatenate され、最終的な出力になります。

ここで、この一行のテキストを具体的なFrame（json）に変換するのが、_getEventsです。普段拡張いただいているこのプログラムの中核部分です。
https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8511
原則として、この関数は依存を持たない（あるテキストを入力して、Frameに変換するだけ）なのですが、この処理のように前後の関係を用いる必要がある処理がどうしても出てきます。

そこで、block_stackという現在処理しているFrameのポインタを保存しておくstackが用意されています。（なぜstackなのかというと、ifなどネストする処理があるため）

使い方は、下記のように、_getEventsから返ってきたframeを下記の形式でpushしておき、

https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8584-L8587

_getEventsから返ってきたframeが特定のコードだった場合、分岐して、stackから取り出し、内部のパラメータをいじってください。https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8564-L8577

ここで、block_stackに積まれているのは、下記ですでにeventCommandListにpushされているFrameの生ポなので、上記のように直接いじると、すでにeventCommandListに積まれているframe自体が変わります。（バグりやすいコードの書き方ですが、致し方ありません......良くも悪くも後戻りできない仕様なので...）
https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8590

\<END\> の処理は下記にしたがってください。
https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L6900-L6910

最後に、ENDのCODEでblock_stackからポインタを削除してください。
https://github.com/Shick1112/Text2Frame-MV/blob/0775706a1c888a5222dac226a80e27f7eab0d0b4/Text2Frame.js#L8522-L8531

**Comment by HidetoshiKawaguchi** [comment]
@yktsr
解説ありがとうございます。私が思っているほど根深い問題ではなさそうで良かったです。

@Shick1112 
実装をストップするようお願いしましたが、yktsrの解説で進められないでしょうか？進められる場合は実装をお願いしたいです。無理そうであれば、再度ご相談いただき、別のタグから実装してもOKです（そもそも順番に指定はありません）。
よろしうお願いします。

**Comment by Shick1112** [comment]
@yktsr
解説ありがとうございます！

@HidetoshiKawaguchi 
自分が実装したいと思います
※ちょっと体調を崩してしまい、ゆっくり気味になると思います

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 
あら、お大事になさってください。仕様を書ききったら、私も実装に参加しようとも考えております。なので、本当にご自身のペースで進めていただければと思います。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 
体調が崩れてしまっているところ申し訳ないです。お身体の調子がいいときに反応していただければと思います。
現在、元のリポジトリ(yktsr:Text2Frame)のdev-220ブランチ(feature/add_all_tagのマージのターゲット）で、コードほぼ全域に跨るコーディング規則に関する修正が入っています。その修正のコミットをfeature/add_all_tagブランチにも早いところマージさせたいところなのですが、何分範囲が範囲なので１００％、この「戦闘の処理」による実装ともほぼコード全域に渡るコンフリクトが発生します。そのため、dev-220の更新をfeature/add_all_tagにいれるタイミングを測っているところでございます。

タイミングを決めるために、Shickさんのこの機能に関する実装の状況をお聞きしたいです。以下のどちらでしょうか。

(1) すでに実装に着手している
(2) まだ実装に着手していない

(1)の場合でしたら、Shickさんが実装を完了してからdev-220の内容をfeature/add_all_tagにマージさせ、現在ある他のイシューに関するブランチも更新します。
(2)の場合でしたら、一旦実装に着手するのを待っていただき、私がfeature/add_all_tagを更新、その後他のブランチも更新したらご連絡するので、それから実装していただきたいです。

体調が優れているときで構いませんので、ご返答いただけますと幸いです。
よろしくお願いします。

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
お疲れ様です。
まだ実装に着手しておりませんので、先にコーディング規則の修正をお願いします。(お手数おかけします)

以上です。よろしくお願いいたします。

**Comment by yktsr** [comment]
コーディング規約の変更がfeature/add_all_tag に入りました。新規実装はこのブランチからcheck outしてください。
新しいコーディング規約はJavaScript standard styleです。対応のvscode pluginもあります。

コマンドラインからのチェックは
npm run lint

自動修正は、
npm run lint — —fix
です

今回のコーディング規約変更で、letとconstの使い分けが厳格になり、immutableな変数にletを使うことが出来なくなりました。特に参照型の変数で、参照先の変数は可変だが、参照自体は不変の場合にconstを使うことに注意してください。
また、RPG Makerの仕様による例外を除き、原則としてvarを使うことは出来ません。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 
お返事ありがとうございます。(2)を実施いたしました。
新たなコーディング規約のものに更新されておりますので、ご都合のよろしいタイミングで実装をよろしくお願いします。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 
五月雨ですみません。私がGitお作法的に良くないことをした可能性があるので、手元のfeature/add_battle_processingブランチは削除いていただいて、新たに持ってきていただいたほうがいいかもしれません。リモートのfeature/add_battle_processingをPULLしたときになにか違和感があるようならそうしてください。
一度リモートのfeature/add_battle_processingブランチを削除してしまって再度新しく作ってしまうことをしたんですよね。よく考えたら良くなかったのかなと。
よろしくお願いします。

**Comment by Shick1112** [comment]
@HidetoshiKawaguchi 
ブランチの更新ありがとうございます！

昨日add_battle_processingをプルした際にエラーが発生したので軽く調べてみたところ、
ローカルとリモートのブランチの履歴が異なる旨のメッセージが出てきました。
プルのオプションでどうにかできる可能性はあったのですが、
誤ってリモート側に影響を与えるようなことをしてしまうのが怖かったので、
新しくadd_battle_processingをチェックアウトをしたら問題なく出来ました。

体調の方も大分落ち着いてきたので、残りのissueを今日から日曜辺りでやっていく予定です。
※体温が38.6度までいっていたので回復に時間がかかりました・・・

以上です。よろしくお願いいたします。

**Comment by HidetoshiKawaguchi** [comment]
@Shick1112 あぁぁ、やはりすでに混乱させてしまっていましたか。申し訳ないです。ご対応いただきありがとうございます。
体調が落ち着いてきたようで何よりでございます。
引き続きよろしくお願いします。
